spring.application.name=ufccursos

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5431/VMF}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin000}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

api.security.token.secret=${JWT_SECRET:PfYqUrxi}

python.service.base-url=${PYTHON_SERVICE_URL:http://localhost:8085}